import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import RootLayout, { metadata } from "./layout";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "font-geist-sans" }),
  Geist_Mono: () => ({ variable: "font-geist-mono" }),
}));

describe("landing root layout", () => {
  it("wraps children with the html shell", () => {
    const layout = RootLayout({ children: <div>landing-child</div> });

    expect(layout.props.lang).toBe("en");
    expect(layout.props.children.props.children.props.children).toBe(
      "landing-child",
    );
  });

  it("keeps metadata export stable", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
